layout_spectrum: 0.9991568
typography_spectrum: 0.5389938
color:
  saturation: 0.7139854
  brandStrength: 0.504844
  lightness: 0.5362563
  rhythmicContrast: 0.51376
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: lalunafilms.co.uk
